{{- if .Values.bitcoinCashNodeTestnet.enable }}
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-cash-node-testnet-service
  labels:
    app: bitcoin-cash-node-testnet
    {{- include "chaingraph.labels" . | nindent 4 }}
spec:
  ports:
    - name: testnet-p2p
      port: 28333
  type: ClusterIP
  selector:
    app: bitcoin-cash-node-testnet
{{- end }}
