{{ $chaingraphPostgresPassword := include "chaingraph.postgresPassword" . }}
{{ $chaingraphHasuraAdminSecretKey := include "chaingraph.hasuraAdminSecretKey" . }}
# Once generated, this chart should preserve secrets across upgrades. As such,
# chaingraph-secrets are always configured, even if not currently being used.
apiVersion: v1
kind: Secret
metadata:
  name: chaingraph-secrets
type: Opaque
data:
  adminSecretKey: {{ $chaingraphHasuraAdminSecretKey  }}
  postgresPassword: {{ $chaingraphPostgresPassword  }}
  postgresConnectionString: {{ print "postgres://" .Values.postgres.username ":" $chaingraphPostgresPassword "@postgres-service." .Release.Namespace ".svc.cluster.local:5432/chaingraph" | b64enc | quote }}
