apiVersion: v1
kind: Service
metadata:
  name: hasura-service
  labels:
    app: hasura
    {{- include "chaingraph.labels" . | nindent 4 }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: hasura
  type: ClusterIP
