{{- if .Values.pgHero.enable }}
apiVersion: v1
kind: Service
metadata:
  name: pghero-service
  labels:
    app: pghero
    {{- include "chaingraph.labels" . | nindent 4 }}
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: pghero
  type: ClusterIP
{{- end }}
