apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    {{- include "chaingraph.labels" . | nindent 4 }}
spec:
  ports:
    - name: postgres
      port: 5432
  type: ClusterIP
  selector:
    app: postgres
